apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: katalog-api
  namespace: stube
  labels:
    app: katalog-api
spec:
  selector:
    matchLabels:
      app: katalog-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
